const data = [
  {
    "Category_ID": "laptop",
    "Description": "لپ‌تاپ قدرتمند مناسب برنامه‌نویسی، طراحی و کارهای روزمره",
    "Discount": 10,
    "Price": 45990000,
    "ProductID": 1001,
    "Product_Name": "ASUS VivoBook 15",
    "Status": "Available",
    "CPU": "Corei5",
    "RAM": "16",
    "Brand": "asus",
    "SalesCount": 125,
    "pic1": "/images/asus-vivobook-15-1.jpg",
    "pic2": "/images/asus-vivobook-15-2.jpg",
    "pic3": "/images/asus-vivobook-15-3.jpg",
    "pic4": "/images/asus-vivobook-15-4.jpg"
  },
  {
    "Category_ID": "laptop",
    "Description": "لپ‌تاپ حرفه‌ای مناسب برنامه‌نویسی و کارهای سنگین",
    "Discount": 15,
    "Price": 68990000,
    "ProductID": 1002,
    "Product_Name": "Lenovo LOQ 15",
    "Status": "Available",
    "CPU": "Corei7",
    "RAM": "16",
    "Brand": "lenovo",
    "SalesCount": 89,
    "pic1": "/images/lenovo-loq-1.jpg",
    "pic2": "/images/lenovo-loq-2.jpg",
    "pic3": "/images/lenovo-loq-3.jpg",
    "pic4": "/images/lenovo-loq-4.jpg"
  },
  {
    "Category_ID": "laptop",
    "Description": "لپ‌تاپ سبک و قدرتمند با طراحی مدرن",
    "Discount": 5,
    "Price": 52990000,
    "ProductID": 1003,
    "Product_Name": "Apple MacBook Air M2",
    "Status": "Available",
    "CPU": "Apple M2",
    "RAM": "8",
    "Brand": "Apple",
    "SalesCount": 156,
    "pic1": "/images/macbook-air-m2-1.jpg",
    "pic2": "/images/macbook-air-m2-2.jpg",
    "pic3": "/images/macbook-air-m2-3.jpg",
    "pic4": "/images/macbook-air-m2-4.jpg"
  },
  {
    "Category_ID": "mobile",
    "Description": "گوشی هوشمند با دوربین قدرتمند و نمایشگر باکیفیت",
    "Discount": 8,
    "Price": 37990000,
    "ProductID": 2001,
    "Product_Name": "Samsung Galaxy S24",
    "Status": "Available",
    "CPU": "Snapdragon 8 Gen 3",
    "RAM": "8GB",
    "Brand": "Samsung",
    "SalesCount": 342,
    "pic1": "/images/galaxy-s24-1.jpg",
    "pic2": "/images/galaxy-s24-2.jpg",
    "pic3": "/images/galaxy-s24-3.jpg",
    "pic4": "/images/galaxy-s24-4.jpg"
  },
  {
    "Category_ID": "mobile",
    "Description": "گوشی پرچمدار اپل با عملکرد سریع و دوربین حرفه‌ای",
    "Discount": 7,
    "Price": 72990000,
    "ProductID": 2002,
    "Product_Name": "iPhone 15 Pro",
    "Status": "Available",
    "CPU": "Apple A17 Pro",
    "RAM": "8GB",
    "Brand": "Apple",
    "SalesCount": 278,
    "pic1": "/images/iphone-15-pro-1.jpg",
    "pic2": "/images/iphone-15-pro-2.jpg",
    "pic3": "/images/iphone-15-pro-3.jpg",
    "pic4": "/images/iphone-15-pro-4.jpg"
  },
  {
    "Category_ID": "pc",
    "Description": "مانیتور گیمینگ با نرخ نوسازی بالا و زمان پاسخ سریع",
    "Discount": 12,
    "Price": 18990000,
    "ProductID": 3001,
    "Product_Name": "ASUS TUF Gaming 27",
    "Status": "Available",
    "CPU": null,
    "RAM": null,
    "Brand": "ASUS",
    "SalesCount": 74,
    "pic1": "/images/asus-tuf-27-1.jpg",
    "pic2": "/images/asus-tuf-27-2.jpg",
    "pic3": "/images/asus-tuf-27-3.jpg",
    "pic4": "/images/asus-tuf-27-4.jpg"
  },
  {
    "Category_ID": "pc",
    "Description": "کیبورد مکانیکی مناسب گیمینگ و استفاده روزمره",
    "Discount": 10,
    "Price": 4290000,
    "ProductID": 4001,
    "Product_Name": "Redragon K552",
    "Status": "Available",
    "CPU": null,
    "RAM": null,
    "Brand": "Redragon",
    "SalesCount": 512,
    "pic1": "/images/redragon-k552-1.jpg",
    "pic2": "/images/redragon-k552-2.jpg",
    "pic3": "/images/redragon-k552-3.jpg",
    "pic4": "/images/redragon-k552-4.jpg"
  },
  {
    "Category_ID": "pc",
    "Description": "ماوس گیمینگ دقیق با طراحی ارگونومیک",
    "Discount": 5,
    "Price": 2890000,
    "ProductID": 4002,
    "Product_Name": "Logitech G502 Hero",
    "Status": "Available",
    "CPU": null,
    "RAM": null,
    "Brand": "Logitech",
    "SalesCount": 687,
    "pic1": "/images/logitech-g502-1.jpg",
    "pic2": "/images/logitech-g502-2.jpg",
    "pic3": "/images/logitech-g502-3.jpg",
    "pic4": "/images/logitech-g502-4.jpg"
  }
];

export { data };